workspace:
  base: "c:/test"
  path: src/github.com/drone/envsubst

clone:
  git:
    image: some_drone_git
    depth: 50

pipeline:
  build:
    image: some_docker
    commands:
      - cd c:\root
      - mkdir c:\root\test
      - dir
      - ls
      - cd c:\
      - dir
      - ls
      - dir c:\test
      - ls c:\test
      - dir c:\test\src\github.com\drone\envsubst
      - ls c:\test\src\github.com\drone\envsubst
